[package]
name    = "with-env"
version = "0.1.0"
edition = "2024"

[dependencies]
clap    = { version = "4.5.35", features = ["derive"] }
dotenvy = { version = "0.15.7" }
execute = { version = "0.2.13" }
eyre    = { version = "0.6.12" }
